name: build
on: [push, pull_request]
jobs:
  android_build:
    runs-on: ubuntu-18.04
    env:
      BUILD_TARGET: android_cmake

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.7.18'
    - uses: actions/setup-node@v2
      with:
        node-version: '12.8.0'
    
    - name: install_android_ndk
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
         curl -O http://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
         unzip -q android-ndk-r16b-linux-x86_64.zip
         mv android-ndk-r16b android-ndk
    
    - name: install_python_module
      run: |
        python -m easy_install pip 
        python -m pip install PyYAML
        python -m pip install Cheetah

    - name: run script
      run: |
        ./tools/travis-scripts/run-script.sh
