name: build
on: [push, pull_request]
jobs:
  android_build:
    runs-on: ubuntu-18.04
    env:
      BUILD_TARGET: android_cmake

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '2.7.18'
    - uses: actions/setup-node@v2
      with:
        node-version: '12.8.0'

    - name: before_install
      run: |
        ./tools/travis-scripts/before-install.sh
    
    - name: run script
      run: |
        ./tools/travis-scripts/run-script.sh
