name: build
on: [push, pull_request]

jobs:
  windows_cmake:
    runs-on: windows-2016
    env:
      BUILD_TARGET: windows_cmake

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Python
    - uses: actions/setup-python@v2
      with:
        python-version: '2'
        run:
          python -V
        
