name: build
on: [push, pull_request]

jobs:
  windows_cmake:
    runs-on: windows-2016
    env:
      BUILD_TARGET: windows_cmake

    steps:
    - uses: actions/checkout@v2
    
    - name: Set Python
    - uses: actions/setup-python@v2
      with:
        python-version: '2'
    
    - name: Set Node
    - uses: actions/setup-node@v2
      with:
        node-version: '12.8.0'
    
    - name: before_install
      run: |
        ./tools/travis-scripts/before-install.sh
        
    - name: run script
      run: |
        ./tools/travis-scripts/run-script.sh

