name: Apply Clang Format

on: [push, pull_request]
#on:
#  pull_request_target:
#    types: [closed]

jobs:
  Clang-Format:
    #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}
        ref: ${{ github.head_ref }}
    
    - uses: fish9167/clang-format-lint-action@v0.12
      with:
        style: file
    
    - uses: fish9167/git-auto-commit-action@v4
      with:
        commit_message: Apply clang-format
        push_options: --force
