name: Clang Tidy - Android

on: pull_request

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Lint code base - Android
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get changed files
        uses: PatriceJiang/paths-filter@master
        id: listchanged
        with:
          list-files: shell
          filters: |
            source:
              - added|modified: '**/*.cpp'
              - added|modified: '**/*.h'
              - added|modified: '**/*.hpp'
              - added|modified: '**/*.m'
              - added|modified: '**/*.mm'
              - added|modified: '**/*.c'
              - exclude: 'cocos/editor-support/dragonbones/**'
              - exclude: 'cocos/base/etc1.*'
              - exclude: 'cocos/base/etc2.*'
            allChanges:
              - added|modified|deleted: '**'
            skipedDebug:
              - added|modified|deleted: '**'
              - exclude: 'cocos/editor-support/dragonbones/**'
      - name: Install CMake & Clang Tidy
        run: |
          sudo apt install -y cmake llvm clang-tidy-11

      - name: Generate Compile database
        shell: bash
        run: |
          EXT_VERSION=`grep version external/config.json  |awk -F'"' '{print $4}'`
          rm external/config.json
          git clone --branch $EXT_VERSION --depth 1 https://github.com/cocos-creator/engine-native-external external
          echo -e "cmake_minimum_required(VERSION 3.8)\nproject(engine_native CXX)\nenable_language(C ASM)" | cat - CMakeLists.txt > tmp.txt
          mv tmp.txt CMakeLists.txt
          cmake -Bbuild -DCC_USE_GLES2=ON -DCC_USE_VULKAN=ON -DCC_USE_GLES3=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE="$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake"  -DANDROID_PLATFORM=android-21 -G"Unix Makefiles"

      - name: Generate clang-fix.yaml
        shell: bash
        if: ${{ steps.listchanged.outputs.source == 'true' }}
        run: |
          CPP="${{ steps.listchanged.outputs.source_files }}"
          FILTERED=`node .github/workflows/filter_by_cdb.js $CPP`
          if [[ "$FILTERED-xxx" == "-xxx" ]]; then
            echo "no source files match"
          else
            clang-tidy-11 --format-style=file -p ./build --export-fixes=clang-fixes.yaml $FILTERED
          fi
      - name: clang-tidy-action
        uses: PatriceJiang/clang-tidy-action@master
        if: hashFiles('clang-fixes.yaml') != ''
        with:
          fixesFile: clang-fixes.yaml
          noFailOnIssue: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          error-limit: 200
