name: Apply Clang Format

#on: [push, pull_request]
on:
  pull_request_target:
    types: [closed]

jobs:
  Clang-Format:
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ github.token }}
        ref: ${{ github.head_ref }}
    
    - id: get_change_files
      uses: fish9167/file-changes-action@v1.2.3
      with:
        output: ' '
        fileOutput: ' '

    - name: get change files
      run: |
        cat $HOME/files.txt
        mv $HOME/files.txt ${{github.workspace}}/files.txt
    
    - uses: fish9167/clang-format-lint-action@master
      with:
        exclude: .clang-format-ignore
        extensions: 'c,h,hpp,cpp,cxx'
        style: file
        inplace: True
        
    - uses: fish9167/git-auto-commit-action@v4
      with:
        commit_message: Apply clang-format
        commit_user_name: cocos-robot
        commit_user_email: cocos-robot@cocos.com
        commit_author: cocos-robot <cocos-robot@cocos.com>
        push_options: --force

